
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  protocol: "http"
  username: 'elastic'
  password: '${ELASTIC_PASSWORD}'

# enabled modules for monitoring (e.g. elasticsearch-xpack)
metricbeat.modules:
- module: system
  metricsets: ["cpu", "load", "memory", "network", "process", "process_summary", "core", "diskio", "socket"]
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  period: 10s
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: '${ELASTIC_PASSWORD}'
setup.kibana:
  host: "${KIBANA_HOST}:80"
  username: elastic
  password: '${ELASTIC_PASSWORD}'